---
- hosts: g23acxwas003.au.ibm.com
  gather_facts: False
  tasks:   
    - name: create logical volume testlv
      command: mklv -t jfs2 -y testlv db2vg 8 
      args:
        creates: /dev/testlv
    
    - name: create filesystem /test
      command: crfs -v jfs2 -A yes -m /test -d /dev/testlv
      args:
        creates: /test
    
    - name: mount /test
      command: mount /test
    
    - name: change permissions on /test
      file: path="/test" mode=0777 owner=root group=system
