---
- hosts: g23acxwas003.au.ibm.com
  user: anstadm
  become: true
  gather_facts: False
  tasks:   
    - name: change permissions on /temp/1022100b.210323.epkg.Z
      file: 
      path: /temp/1022100b.210323.epkg.Z mode=0777 owner=mrara group=staff

    - name:  update openssl packages on the server
      command: emgr -e 1022100b.210323.epkg.Z -p
