---
- hosts: g23acxwas003.au.ibm.com
  user: anstadm
  become: true
  gather_facts: False
  tasks:
    - name: Install EFIX
      shell: 
       cmd: emgr -e 1022100b.210323.epkg.Z -p
       file: path="/temp/1022100b.210323.epkg.Z"
      tags: install_efix
