---
- hosts: g23acxwas003.au.ibm.com
  user: anstadm
  become: true
  gather_facts: False
  tasks:   
    - name: change permissions on /opt/IBM/cobalt
      file: path="/opt/IBM/cobalt" mode=0777 owner=mrara group=staff recurse=yes
