---
- hosts: g23acxwas003.au.ibm.com
  user: anstadm
  become: true
  gather_facts: False
  tasks:   
    - name: change permissions on /opt/IBM/cobalt
      file: dest=/opt/IBM/cobalt owner=mrara group=staff mode=u=rwX,g=rX,o=rX recurse=yes
