---
- hosts: g23acxwas003.au.ibm.com
  gather_facts: False
  tasks:
    - name: Increase size of a filesystem
      aix.filesystem:
        filesystem: /opt/IBM/cobalt
        state: present
        attributes: size=+5M
