---
- hosts: g23acxwas003.au.ibm.com
  gather_facts: False
  tasks:  
    - name: change permissions on /test1
      file: path="/test1" mode=0777 owner=root group=system 
    - name: mount file system /test1
      mount: name=/test1 src=/dev/testlv state=mounted fstype=jfs2
