---
- hosts: g23acxwas003.au.ibm.com
  gather_facts: False
  tasks:   
    - name: change permission on /opt/IBM/cobalt
      command: chmod 0777 /opt/IBM/cobalt

    - name: change owner and group on /opt/IBM/cobalt
      command: chown root:system /opt/IBM/cobalt
      args:
