---
- hosts: g23acxwas003.au.ibm.com
  gather_facts: False
  tasks:
    - name: Creation of a JFS2 filesystem
      aix.filesystem:/test
        state: present
        filesystem: /test
        fs_type: jfs2
        attributes: size=8,isnapshot='no'
        mount_group: testlv
        vg: db2vg
