---
- hosts: all
  gather_facts: no
  tasks:
    - shell: lspv
      register: lspv

    # Print the shell task's stdout.
    - debug: msg={{ lspv.stdout }}

    # Print all contents of the shell task's output.
    - debug: var=lspv
